// Expo's canonical Metro config. Generated by `npx expo customize` and
// kept as-is — no custom resolver tweaks. Having this file (extending
// `expo/metro-config`) keeps `expo-doctor`'s metro-config check green
// in CI; removing it brings the check back to red.
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = config;
